export default  {
    TEXT_PRIMARY: '#1D2027',
    TEXT_SECONDARY: '#797979',
    GREEN: '#2ED184',
    
    BACKGROUND_PRIMARY: '#F8F9FD',
    BACKGROUND_SHADOWED: '#F3F5F9',
    BACKGROUND_ACCENT: '#FFFFFF',
}